# Generated by Django 5.2.3 on 2025-06-27 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=43200), null=True),
        ),
    ]
