# Generated by Django 5.2.3 on 2025-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
