# Generated by Django 5.2.3 on 2025-06-27 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=43200)),
        ),
    ]
